### ISSUE TITLE
Subscription always returns online first, even when offline.

### ISSUE THREAD

**Issue by frcerror404** [cyrilletuzi/ngx-pwa-offline#15]
When subscribing to the onlineChanges observable, it will always return true for the first event.

Example code:
``` 
constructor(private network: Network) {
    this.onlineSubscription = network.onlineChanges.subscribe(online => {
       if(online) {
          this.sync(); // will always return true the first time, even offline
        }
      });
}
```

The fix that I used was to just use the network.online boolean in the subscription instead of the observer result.

``` 
constructor(private network: Network) {
    this.onlineSubscription = network.onlineChanges.subscribe(online => {
       if(network.online) { // this will return false if it's not online, even the first time
          this.sync(); 
        }
      });
}
```

**Comment by cyrilletuzi** [comment]
Thanks for your feedback and sorry for the delay (I don't receive notifications for this repo).

As mentioned in the README, "be aware the online status is provided by the browser and it is not always reliable: for example, if your computer is connected to a network but with no Internet access, the browser will still says it's online."

And the lib can't do better than the browser (except going into hard solutions like pinging, which is not considered in this lib).

So I'm closing the issue for now. If you can provide information that shows that it's a real bug and not an expected false positive, I'll reopen the issue.

**Comment by cyrilletuzi** [comment]
Sorry for the delay (I don't receive notifications for this repo) and also sorry for the last message (read the issue too quickly).

Can you explain in details your steps to have this result?

Indeed, as `onlineChanges ` is asynchronous, it may be a timing issue (online when the `Observable` emits and then offline a few (micro)seconds later).

**Comment by cyrilletuzi** [comment]
Closing for housekeeping. Feel free to comment and I'll reopen this issue.
