### ISSUE TITLE
always online when running in Android

### ISSUE THREAD

**Issue by jonathan-chin** [cyrilletuzi/ngx-pwa-offline#18]
I'm running this in an Ionic v4 app. On browser and iOS, it correctly detects when I'm online / offline. However, when I run it on Android 9, it always returns true.

```
network.onlineChanges.subscribe(online => {
            alert(online);
        });
```

**Comment by cyrilletuzi** [comment]
Sorry for the delay (I don't receive notifications for this repo).

Can you explain your steps to test the offline scenario? As `onlineChanges` is asynchronous, timing is important.

Also, as mentionned in the README, "be aware the online status is provided by the browser and it is not always reliable: for example, if your computer is connected to a network but with no Internet access, the browser will still says it's online."

**Comment by cyrilletuzi** [comment]
Closing for housekeeping. Feel free to comment and I'll reopen this issue.
