### ISSUE TITLE
Error: TS2305

### ISSUE THREAD

**Issue by sirusdas** [cyrilletuzi/ngx-pwa-offline#2]
ERROR in node_modules/@ngx-pwa/local-storage/src/service/databases/indexeddb-database.d.ts(1,10): error TS2305: Module '"/xxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-pwa/local-storage/src/service/databases/indexeddb-database.d.ts(2,10): error TS2305: Module '"/xxx/node_modules/rxjs/ReplaySubject"' has no exported member 'ReplaySubject'.
node_modules/@ngx-pwa/local-storage/src/service/databases/local-database.d.ts(1,10): error TS2305: Module '"/xxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-pwa/local-storage/src/service/databases/localstorage-database.d.ts(1,10): error TS2305: Module '"/xxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-pwa/local-storage/src/service/databases/mock-local-database.d.ts(1,10): error TS2305: Module '"/xxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-pwa/local-storage/src/service/lib.service.d.ts(1,10): error TS2305: Module '"/xxx/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/ReplaySubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/ReplaySubject'.

I have never seen this error before in my life! Some one please explain this and also let me know the fix!

**Comment by cyrilletuzi** [comment]
You're not in the good project.

**Comment by cyrilletuzi** [comment]
That means that `src/service/databases/indexeddb-database.d.ts` and all other files referenced in your error message are not part of this library. It's files from `@ngx-pwa/local-storage`.

**Comment by sirusdas** [comment]
Thanks Sir!🙏
