### ISSUE TITLE
Does not work by disconnecting from the cable Internet

### ISSUE THREAD

**Issue by rruffer** [cyrilletuzi/ngx-pwa-offline#26]
It works when I switch from devtools to offline. But when I disconnect the internet cable, it doesn't recognize it. Continue online

- `@ngx-pwa/offline` version: @ngx-pwa/offline@10
- Angular version (`ng version`): 10.0.4

**Comment by cyrilletuzi** [comment]
The library does not detect Internet connection by itself, it just uses native `navigator.onLine` API. So:
- what browser and version are you using?
- what is the result in your browser console if you run `console.log(navigator.onLine)`?

A reminder from the readme:
> be aware the online status is provided by the browser and it is not always reliable: for example, if your computer is connected to a network but with no Internet access, the browser will still says it's online.

**Comment by rruffer** [comment]
what browser and version are you using?
Chrome 85.0.4183.83

what is the result in your browser console if you run console.log (navigator.onLine)?

console.log (navigator.onLine) always returns true. either disconnected or connected. I tested on chrome, firefox, edge and it gives the same thing.

**Comment by cyrilletuzi** [comment]
Then the lib is working as expected, as unfortunately it cannot do better than the browser itself. So I will close this issue, as nothing is actionnable on the lib side.

But note that what you tried to do is not a real life scenario. A real user will not disconnect his/her Internet cable. The connection may be lost for some other reasons, and in those cases the browser should react more correctly.
