### ISSUE TITLE
When an application is online

### ISSUE THREAD

**Issue by utillity** [cyrilletuzi/ngx-pwa-offline#30]
Actually this is just a comment on how I check/know if I'm online or offline:

I open up an EventSource (Server-Side-Events) to my API (or APIs) and on the connection/disconnection/error events I set wether I am online or not. This way it doesn't matter what the browser thinks. Maybe my API is rechable via the LAN? Maybe the internet is accessible but my API isn't? So what's the point in checking "something is online" if you can't tell from that if your API is reachable anyways.

I hope this helps others how to make a better ONLINE/OFFLINE discovery

**Comment by utillity** [comment]
Alternative, if the respective API does not exponse any SSE, just call a ping (or equivalent) API method regularily and set the state according to response/outcome of that call

**Comment by cyrilletuzi** [comment]
Hi, thanks for your comment.

While I agree and I'm also frustrated by the quite unreliable browser behavior, your solutions require more configuration both on client side and server side, and are clearly out of scope of this small library.
